Controllers/AdminController.cs
using System.Linq;
using System;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc;
using System.Web;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using PartsCatalog.Models;
using PartsCatalog.Repositories;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using PartsCatalog.Data;

namespace PartsCatalog.Controllers
{
    [Authorize(Roles = "Admins")]
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext context;

        private readonly IProductRepository productRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly IClientRepository clientRepository;
        private UserManager<AppUser> userManager;
        private IUserValidator<AppUser> userValidator;
        private IPasswordValidator<AppUser> passwordValidator;
        private IPasswordHasher<AppUser> passwordHasher;

        public AdminController(IPasswordHasher<AppUser> passwordHasher, IPasswordValidator<AppUser> passwordValidator,
                                IUserValidator<AppUser> userValidator, UserManager<AppUser> userManager, 
                                    ApplicationDbContext context, IClientRepository clientRepository, IProductRepository productRepository,
                                     ICategoryRepository categoryRepository)
        {
            this.categoryRepository = categoryRepository;
            this.productRepository = productRepository;
            this.clientRepository = clientRepository;
            this.userManager = userManager;
            this.passwordHasher = passwordHasher;
            this.passwordValidator = passwordValidator;
            this.userValidator = userValidator;
            this.context = context;
        }

        //Main Page

        public ViewResult AdminHomePage()
            => View(context.Products.Include(c => c.Category));

        //Products

        public ViewResult AddOrEditProduct(int productId)
        {
            IEnumerable<SelectListItem> categories = categoryRepository.Categories.Select(c => new SelectListItem
            {
                Value = c.CategoryId.ToString(),
                Text = c.Name
            });
            ViewBag.Categories = categories;

            return View(productRepository.Products.FirstOrDefault(p => p.ProductId == productId));
        }


        [HttpPost]
        public IActionResult AddOrEditProduct(Product product)
        {
            ModelState.Remove("ProductId");

            if (ModelState.IsValid)
            {
                productRepository.SaveProduct(product);
                TempData["message"] = $"Zapisano {product.Name}.";
                return RedirectToAction("AdminHomePage");
            }
            else
            {
                IEnumerable<SelectListItem> categories = categoryRepository.Categories.Select(c => new SelectListItem
                {
                    Value = c.CategoryId.ToString(),
                    Text = c.Name
                });
                ViewBag.Categories = categories;

                return View(product);
            }
        }

        [HttpPost]
        public IActionResult DeleteProduct(int productId)
        {
            if (productRepository.Products
                .FirstOrDefault(p => p.ProductId == productId) != null)
            {
                productRepository.DeleteProduct(productId);
            }
            //Product deletedProduct = productRepository.DeleteProduct(productId);
            return RedirectToAction("AdminHomePage");
        }

        //Categories

        public ViewResult ListCategories()
            => View(context.Categories);

        public IActionResult AddOrEditCategory(int categoryId)
            => View(categoryRepository.Categories.FirstOrDefault(c => c.CategoryId == categoryId));
                                                    
        [HttpPost]
        public IActionResult AddOrEditCategory(Category category)
        {
            ModelState.Remove("CategoryId");

            if (ModelState.IsValid)
            {
                categoryRepository.SaveCategory(category);
                TempData["message"] = $"Zapisano {category.Name}.";
                return RedirectToAction("ListCategories");
            }
            else
            {
                TempData["message"] = $"Nie Zapisano.";
                return View(category);
            }
            
        }

        [HttpPost]
        public IActionResult DeleteCategory(int categoryId)
        {
            categoryRepository.DeleteCategory(categoryId);
            return RedirectToAction("ListCategories");
        }


        //Clients

        public ViewResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateModel model)
        {
            if (ModelState.IsValid)
            {
                AppUser user = new AppUser
                {
                    UserName = model.Login,
                    Email = model.Email
                };

                IdentityResult result = await userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListClients");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("ListClients");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "User not found");
            }
            return View("ListClients", userManager.Users);
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }

        public async Task<IActionResult> Edit(string id)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            
            if (user != null)
            {   

                return View(user);
            }
            else
            {
                return RedirectToAction("ListClients");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, string email, string password)
        {
            AppUser user = await userManager.FindByIdAsync(id);
            
            if (user != null)
            {
                user.Email = email;
                IdentityResult validEmail = await userValidator.ValidateAsync(userManager, user);
                if (!validEmail.Succeeded)
                {
                    AddErrorsFromResult(validEmail);
                }
                IdentityResult validPass = null;
                if (!string.IsNullOrEmpty(password))
                {
                    validPass = await passwordValidator.ValidateAsync(userManager, user, password);
                    if (validPass.Succeeded)
                    {
                        user.PasswordHash = passwordHasher.HashPassword(user, password);
                    }
                    else
                    {
                        AddErrorsFromResult(validPass);
                    }
                }
                if ((validEmail.Succeeded && validPass == null) || (validEmail.Succeeded && password != string.Empty && validPass.Succeeded))
                {
                    IdentityResult result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("ListClients");
                    }
                    else
                    {
                        AddErrorsFromResult(result);
                    }
                }
            }
            else
            {
                
                ModelState.AddModelError("", "User not found");
            }
            return View(user);
        }

        public ViewResult ListClients()
            //=> View(context.Clients);
            => View(userManager.Users);

        public IActionResult AddOrEditClient(int clientId)
            => View(clientRepository.Clients.FirstOrDefault(c => c.ClientId == clientId));
                                                    
        [HttpPost]
        public IActionResult AddOrEditClient(Client client)
        {
            ModelState.Remove("ClientId");

            if (ModelState.IsValid)
            {
                clientRepository.SaveClient(client);
                TempData["message"] = $"Zapisano {client.Name}.";
                return RedirectToAction("ListClients");
            }
            else
            {
                TempData["message"] = $"Nie Zapisano.";
                return View(client);
            }
            
        }

        [HttpPost]
        public IActionResult DeleteClient(int clientId)
        {
            clientRepository.RemoveClient(clientId);
            return RedirectToAction("ListClients");
        }

        //Orders

        public ViewResult ListOrders()
            => View(context.Orders);
    
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using PartsCatalog.Models;
using System.Linq;
using PartsCatalog.Repositories;
using PartsCatalog.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System;
using PartsCatalog.Data;

namespace PartsCatalog.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository orderRepository;
        private readonly AppIdentityDbContext context;
        private Cart cart;
        private UserManager<AppUser> userManager;
        // private readonly IAppUserRepository;

        public OrderController(IOrderRepository orderRepository, Cart cart, UserManager<AppUser> userManager, AppIdentityDbContext context)
        {
            this.orderRepository = orderRepository;
            this.cart = cart;
            this.userManager = userManager;
            this.context = context;
            
        }

        public ViewResult List()
        {
            return View(new ListOrdersViewModel
            {
                Orders = orderRepository.Orders.Where(o => !o.Shipped),
                Users = userManager.Users
            });
        }
            

        public ViewResult ListHistory() =>
            View(orderRepository.Orders);


        [HttpPost]
        public IActionResult MarkShipped(int orderId)
        {
            Order order = orderRepository.Orders  
                            .FirstOrDefault(o => o.OrderID == orderId);
            
            if (order != null)
            {
                order.Shipped = true;
                orderRepository.SaveOrder(order);
            }
            return RedirectToAction(nameof(List));
        }

        public async Task<AppUser> GetCurrentUser()
        {
            var s = await userManager.GetUserAsync(HttpContext.User);
            return s;
        }
  
        [HttpGet]
        public ViewResult CheckoutWithOutAccount()
        { 
            
            string currentUser = userManager.GetUserName(HttpContext.User);
            var currentUserFiltred = userManager.Users.FirstOrDefault(p => p.UserName == currentUser);
            return View(new CheckoutViewModel
            {
                User = currentUserFiltred,
                Order = new Order()
            });
                
        }

        [HttpPost]
        public IActionResult CheckoutWithOutAccount(CheckoutViewModel checkoutViewModel, string returnUrl)
        {

            Order order = new Order();
            
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, Your cart is empty");
                //tempdata pustykoszyk
                return RedirectToAction("ListProducts", "User");
            }
            
            if (ModelState.IsValid)
            {
                order.userId = null;
                order.Lines = cart.Lines.ToArray();
                orderRepository.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(order);
            }
        }



        [HttpGet]
        public ViewResult Checkout()
        { 
            
            string currentUser = userManager.GetUserName(HttpContext.User);
            var currentUserFiltred = userManager.Users.FirstOrDefault(p => p.UserName == currentUser);
            return View(new CheckoutViewModel
            {
                User = currentUserFiltred,
                Order = new Order()
            });
                
        }

        [HttpPost]
        public IActionResult Checkout(CheckoutViewModel checkoutViewModel, string returnUrl)
        {
            string currentUser = userManager.GetUserName(HttpContext.User);
            var currentUserFiltred = userManager.Users.FirstOrDefault(p => p.UserName == currentUser);

            Order order = new Order();
            
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, Your cart is empty");
                //tempdata pustykoszyk
                return RedirectToAction("ListProducts", "User");
            }
            
            if (ModelState.IsValid)
            {
                order.userId = currentUserFiltred.Id;
                order.Lines = cart.Lines.ToArray();
                orderRepository.SaveOrder(order);
                
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(order);
            }
        }

        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }

    }
}

Views/Shared/_AdminLayout.cshtml
<head>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>


<link rel="stylesheet" href="/css/styles.css" asp-append-version="true" />

<style>
.input-validation-error { border-color: red; background-color: #fee; }
</style>

<script src="lib/jquery/dist/jquery.min.js"></script>
<script src="lib/jquery-validation/dist/jquery.validate.min.js">
</script>
<script src="lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

</head>



<ul class="main-navigation">
 
  <li style="margin-bottom: 0%;"><a href="https://localhost:5001/Admin/AdminHomePage">Products</a>
    <ul>
      <li>
        @using (Html.BeginForm("AdminHomePage", "Admin", FormMethod.Post))
        {
         <a><button type="submit" style="border:none; background:transparent;"><p style="color:white">List</p></button></a>
        }
      
      </li>
      <li>
        @using (Html.BeginForm("AddOrEditProduct", "Admin", FormMethod.Get))
        {
         <a><button type="submit" style="border:none; background:transparent;"><p style="color:white">Add product</p></button></a>
        }
      
      </li>
    </ul>
  </li>
  <li><a href="">Categories
    @using (Html.BeginForm("ListCategories", "Admin", FormMethod.Post))
        {
          <button type="submit" style="background:transparent; border:none; color:transparent;" ></button>  
        }
  </a>
    <ul>
      <li>
        @using (Html.BeginForm("ListCategories", "Admin", FormMethod.Post))
        {
         <a><button type="submit" style="border:none; background:transparent;"><p style="color:white">List</p></button></a>
        }
      </li>
      <li>
        @using (Html.BeginForm("AddOrEditCategory", "Admin", FormMethod.Get))
        {
         <a><button type="submit" style="border:none; background:transparent;"><p style="color:white">Add Category</p></button></a>
        }
      </li>
    </ul>
  </li>
  <li><a href="">Users
    @using (Html.BeginForm("ListClients", "Admin", FormMethod.Post))
        {
          <button type="submit" style="background:transparent; border:none; color:transparent;" ></button>  
        }
  </a>
    <ul>
      <li>
        @using (Html.BeginForm("ListClients", "Admin", FormMethod.Post))
        {
         <a><button type="submit" style="border:none; background:transparent;"><p style="color:white">List users</p></button></a>
        }
      </li>
      <li>
        @using (Html.BeginForm("AddOrEditClient", "Admin", FormMethod.Get))
        {
         <a><button type="submit" style="border:none; background:transparent;"><p style="color:white">Add user</p></button></a>
        }
      </li>
      <li>
        @using (Html.BeginForm("Index", "RoleAdmin", FormMethod.Get))
        {
         <a><button type="submit" style="border:none; background:transparent;"><p style="color:white">User Roles</p></button></a>
        }
      </li>
    </ul>
  </li>
  <li><a href="">Orders
    @using (Html.BeginForm("List", "Order", FormMethod.Post))
        {
          <button type="submit" style="background:transparent; border:none; color:transparent;" ></button>  
        }
  </a>
    <ul>
     <li>
        @using (Html.BeginForm("List", "Order", FormMethod.Post))
        {
         <a><button type="submit" style="border:none; background:transparent;"><p style="color:white">List orders</p></button></a>
        }
      </li>
      
    </ul>
  </li>
  <ul class="nav justify-content-end">
  <li style="margin-right: 1%;">
    @if (User.Identity.IsAuthenticated)
    {
      <a style="text-align: right;"  asp-action="Logout" asp-controller="Account" >Wyloguj</a>
      <div ><small>Zalogowany jako: @User.Identity.Name</small></div>
    } else
    {
       <a  asp-action="Login" asp-controller="Account">Zaloguj</a>
    }
   
  </li>

  </ul>
</ul>
      @* <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> *@
    </div>
    
    

@if (!Context.Request.Path.Equals("/Admin/ListClients")) {
  <div style="margin-left:20%;margin-right:20%; margin-top:2%;">
    @RenderBody()
  </div>
}

<div style="margin-left:1%;margin-right:1%; margin-top:2%;" >

@if (TempData["message"] != null) {
  <div class="alert alert-success mt-1">@TempData["message"]</div>
}

@RenderBody()
</div>

Views/Shared/_Layout.cshtml
<head>

<link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>


<link rel="stylesheet" href="/css/styles.css" asp-append-version="true" />
<link rel="stylesheet" href="/css/modal.css" asp-append-version="true" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<style>
.input-validation-error { border-color: red; background-color: #fee; }
</style>

<script src="lib/jquery/dist/jquery.min.js"></script>
<script src="lib/jquery-validation/dist/jquery.validate.min.js">
</script>
<script src="lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

</head>



<ul  class="nav justify-content-end">
  
  


  @* <li style=""><a href="#">@using (Html.BeginForm("Cart", "Index", FormMethod.Post))
        {
         <a><button type="submit" style="border:none; background:transparent;"><p style="color:white">Your cart</p></button></a>
        }
      </a>
  </li>*@
  <li>
    <a style="text-align: right;" asp-action="Index" asp-controller="Cart">
      <div style="font-size: 50px;">
        <i style="margin-left: 0%;" class="fa fa-shopping-cart "></i>
      </div>
    </a>
  
  </li>
  <li style="margin-right: 1%;"> 
    

  @if (User.Identity.IsAuthenticated)
    {
      <a style="text-align: right;" asp-action="Logout" asp-controller="Account">Wyloguj</a>
      <div ><small>Zalogowany jako: @User.Identity.Name</small></div>
    } 
  else
    {
      <a  asp-action="Login" asp-controller="Account">Zaloguj</a>
    }

  </li>

</ul>




      @* <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> *@
    
    
    

<div style="margin-left:25%;margin-right:25%; margin-top:2%;">

@if (TempData["message"] != null) {
<div class="alert alert-success mt-1">@TempData["message"]</div>
}
@RenderBody()
</div>